[build]
  # Path confirmed to work
  publish = "dist/public" 
  # Command confirmed to work
  command = "npm run build"

# 👇 ADD THIS SECTION 👇
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200